### PR TITLE
feat(cli): add check-links-using-get option

### LINKED ISSUE #1: Pass --http-always-get to link-checker?
For some reason, Google-hosted websites such as https://www.chromestatus.com and https://bugs.chromium.org return HTTP 405 when a HEAD request is sent to them. This causes spec validation to fail in e.g. https://github.com/w3c/wake-lock (e.g. https://travis-ci.org/w3c/wake-lock/builds/528742323):

```
could not fetch external page: Error: Method Not Allowed (Code: 405) from output.html to https://chromestatus.com/features/4636879949398016
```

I wonder if making link-checker default to sending GET requests is an acceptable workaround.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #1 

@rakuco r?

### CODE REVIEW

**Comment by rakuco** [comment]
Looks fine to me. This does place the burden of choosing whether to pass this option to each spec, but I guess it's OK?

**Comment by marcoscaceres** [comment]
> Looks fine to me. This does place the burden of choosing whether to pass this option to each spec, but I guess it's OK?

Yes, but relatively few specs are using the validator at the moment... if we find it's useful, we can make it the default. 

Thanks for the review!

**Comment by marcoscaceres** [comment]
will publish it now...

**Comment by rakuco** [comment]
Thanks for the very fast fix :-)

**Pull request merged**
